### ISSUE TITLE
Error when running migrate and collectstatic

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#284]
Hi @dimasciput 

# Problem

## Migrations fail

I've been trying out your changes here locally against a snapshot of the live db. Currently migrate is failing because of some unique constraints that need to be added in the migration (they are missing from the current live tables for some reason):

I manually fixed it by running these SQL commands:

```
ALTER TABLE auth_user ADD CONSTRAINT unique__auth_user__id UNIQUE (id);
ALTER TABLE django_site ADD CONSTRAINT unique__django_site__id UNIQUE (id);

```

## Collect static fails

Also, collect static is failing for me with:

```
Post-processing 'grappelli/stylesheets/screen.css' failed!

DEBUG 2016-04-14 22:17:17,066 base 57 139911251031808 Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f3f88e507d0>
DEBUG 2016-04-14 22:17:17,257 base 57 139911251031808 Sending message of length 2108 to http://sentry.kartoza.com/api/8/store/
DEBUG 2016-04-14 22:17:17,269 base 57 139911251031808 Sending message of length 3015 to http://sentry.kartoza.com/api/8/store/
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
ERROR 2016-04-14 22:17:19,165 base 57 139910865270528 Sentry responded with an error: timed out (url: http://sentry.kartoza.com/api/8/store/)
{u'culprit': u'django.contrib.staticfiles.management.commands.collectstatic in collect',
 u'event_id': u'a8bac11989794310911826d7e39a352d',
 u'exception': {u'values': [{u'module': u'exceptions',
                             u'stacktrace': {u'frames': [{u'abs_path': u'/usr/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py',
                                                          u'context_line': u'            return original_func(self, *args, **kwargs)',
                                                          u'filename': u'raven/contrib/django/management/__init__.py',
                                                          u'function': u'new_execute',
                                                          u'in_app': False,
                                                          u'lineno': 41,
                                                          u'module': u'raven.contrib.django.management',
                                                          u'post_context': [u'        except Exception:',
                                                                            u'            from raven.contrib.django.models import client',
                                                                            u'',
                                                                            u'            client.captureException(extra={',
                                                                            u"                'argv': sys.argv"],
                                                          u'pre_context': [u'        return False',
                                                                           u'',
                                                                           u'    @wraps(original_func)',
                                                                           u'    def new_execute(self, *args, **kwargs):',
                                                                           u'        try:'],
                                                          u'vars': {u'args': [],
                                                                    u'client': u'<raven.contrib.django.client.DjangoClient object at 0x7f3f896d1e50>',
                                                                    u'kwargs': {u"'clear'": False,
                                                                                u"'dry_run'": False,
                                                                                u"'ignore_patterns'": [u"u'CVS'",
                                                                                                       u"u'.*'",
                                                                                                       u"u'*~'"],
                                                                                u"'interactive'": False,
                                                                                u"'link'": False,
                                                                                u"'no_color'": False,
                                                                                u"'post_process'": True,
                                                                                u"'pythonpath'": None,
                                                                                u"'settings'": None,
                                                                                u"'traceback'": False,
                                                                                u"'use_default_ignore_patterns'": True,
                                                                                u"'verbosity'": 1},
                                                                    u'original_func': u'<unbound method BaseCommand.execute>',
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/management/base.py',
                                                          u'context_line': u'            output = self.handle(*args, **options)',
                                                          u'filename': u'django/core/management/base.py',
                                                          u'function': u'execute',
                                                          u'in_app': False,
                                                          u'lineno': 445,
                                                          u'module': u'django.core.management.base',
                                                          u'post_context': [u'            if output:',
                                                                            u'                if self.output_transaction:',
                                                                            u'                    # This needs to be imported here, because it relies on',
                                                                            u'                    # settings.',
                                                                            u'                    from django.db import connections, DEFAULT_DB_ALIAS'],
                                                          u'pre_context': [u'        try:',
                                                                           u'            if (self.requires_system_checks and',
                                                                           u"                    not options.get('skip_validation') and  # Remove at the end of deprecation for `skip_validation`.",
                                                                           u"                    not options.get('skip_checks')):",
                                                                           u'                self.check()'],
                                                          u'vars': {u'args': [],
                                                                    u'options': {u"'clear'": False,
                                                                                 u"'dry_run'": False,
                                                                                 u"'ignore_patterns'": [u"u'CVS'",
                                                                                                        u"u'.*'",
                                                                                                        u"u'*~'"],
                                                                                 u"'interactive'": False,
                                                                                 u"'link'": False,
                                                                                 u"'no_color'": False,
                                                                                 u"'post_process'": True,
                                                                                 u"'pythonpath'": None,
                                                                                 u"'settings'": None,
                                                                                 u"'traceback'": False,
                                                                                 u"'use_default_ignore_patterns'": True,
                                                                                 u"'verbosity'": 1},
                                                                    u'saved_locale': u"'en-us'",
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>',
                                                                    u'translation': u"<module 'django.utils.translation' from '/usr/local/lib/python2.7/site-packages/django/utils/translation/__init__.pyc'>"}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'context_line': u'        collected = self.collect()',
                                                          u'filename': u'django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'function': u'handle',
                                                          u'in_app': False,
                                                          u'lineno': 168,
                                                          u'module': u'django.contrib.staticfiles.management.commands.collectstatic',
                                                          u'post_context': [u"        modified_count = len(collected['modified'])",
                                                                            u"        unmodified_count = len(collected['unmodified'])",
                                                                            u"        post_processed_count = len(collected['post_processed'])",
                                                                            u'',
                                                                            u'        if self.verbosity >= 1:'],
                                                          u'pre_context': [u'        )',
                                                                           u'',
                                                                           u"        if self.interactive and input(''.join(message)) != 'yes':",
                                                                           u'            raise CommandError("Collecting static files cancelled.")',
                                                                           u''],
                                                          u'vars': {u'destination_path': u"'/home/web/static'",
                                                                    u'message': [u"u'\n'",
                                                                                 u"u'You have requested to collect static files at the destination\nlocation as specified in your settings'",
                                                                                 u"u':\n\n    /home/web/static\n\n'",
                                                                                 u"u'This will overwrite existing files!\n'",
                                                                                 u"u'Are you sure you want to do this?\n\nType 'yes' to continue, or 'no' to cancel: '"],
                                                                    u'options': {u"'clear'": False,
                                                                                 u"'dry_run'": False,
                                                                                 u"'ignore_patterns'": [u"u'CVS'",
                                                                                                        u"u'.*'",
                                                                                                        u"u'*~'"],
                                                                                 u"'interactive'": False,
                                                                                 u"'link'": False,
                                                                                 u"'no_color'": False,
                                                                                 u"'post_process'": True,
                                                                                 u"'pythonpath'": None,
                                                                                 u"'settings'": None,
                                                                                 u"'traceback'": False,
                                                                                 u"'use_default_ignore_patterns'": True,
                                                                                 u"'verbosity'": 1},
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'context_line': u'                    raise processed',
                                                          u'filename': u'django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'function': u'collect',
                                                          u'in_app': False,
                                                          u'lineno': 120,
                                                          u'module': u'django.contrib.staticfiles.management.commands.collectstatic',
                                                          u'post_context': [u'                if processed:',
                                                                            u'                    self.log("Post-processed \'%s\' as \'%s\'" %',
                                                                            u'                             (original_path, processed_path), level=1)',
                                                                            u'                    self.post_processed_files.append(original_path)',
                                                                            u'                else:'],
                                                          u'pre_context': [u'                if isinstance(processed, Exception):',
                                                                           u'                    self.stderr.write("Post-processing \'%s\' failed!" % original_path)',
                                                                           u"                    # Add a blank line before the traceback, otherwise it's",
                                                                           u'                    # too easy to miss the relevant part of the error message.',
                                                                           u'                    self.stderr.write("")'],
                                                          u'vars': {u'finder': u'<django.contrib.staticfiles.finders.AppDirectoriesFinder object at 0x7f3f89999d10>',
                                                                    u'handler': u'<bound method Command.copy_file of <django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>>',
                                                                    u'original_path': u"u'grappelli/stylesheets/screen.css'",
                                                                    u'path': u"u'js/github-issue.js'",
                                                                    u'prefixed_path': u"u'js/github-issue.js'",
                                                                    u'processed': u'ValueError(u"The file \'admin/img/icon-deletelink.svg\' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.",)',
                                                                    u'processed_path': None,
                                                                    u'processor': u'<generator object post_process at 0x7f3f8994d780>',
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>',
                                                                    u'storage': u'<django.core.files.storage.FileSystemStorage object at 0x7f3f89999850>'}}]},
                             u'type': u'ValueError',
                             u'value': u"The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>."}]},
 u'extra': {u'argv': [u"'manage.py'", u"'collectstatic'", u"'--noinput'"],
            u'sys.argv': [u"'manage.py'", u"'collectstatic'", u"'--noinput'"]},
 u'level': 40,
 u'message': u"ValueError: The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.",
 u'modules': {u'allauth': u'0.25.2',
              u'crispy_forms': u'1.4.0',
              u'django': u'1.8.12',
              u'django_countries': u'3.4.1',
              u'django_hashedfilenamestorage': u'1.0',
              u'easy_thumbnails': u'2.3',
              u'embed_video': u'1.0.0',
              u'grappelli': u'2.8.1',
              u'python': u'2.7.10',
              u'raven': u'5.8.1',
              u'reversion': u'1.9.3',
              u'rosetta': u'0.7.0'},
 u'platform': u'python',
 u'project': u'8',
 u'server_name': u'uwsgi',
 u'tags': {u'site': u'changelog.kartoza.com'},
 u'time_spent': None,
 u'timestamp': u'2016-04-14T20:17:17Z'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 162, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
ERROR 2016-04-14 22:17:19,170 base 57 139910865270528 [u"ValueError: The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.", u'  File "raven/contrib/django/management/__init__.py", line 41, in new_execute', u'  File "django/core/management/base.py", line 445, in execute', u'  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle', u'  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect']
ERROR 2016-04-14 22:17:21,976 base 57 139910865270528 Sentry responded with an error: timed out (url: http://sentry.kartoza.com/api/8/store/)
{u'culprit': u'django.contrib.staticfiles.management.commands.collectstatic in collect',
 u'event_id': u'd1b1eda132dc486585096bbc40ac5951',
 u'exception': {u'values': [{u'module': u'exceptions',
                             u'stacktrace': {u'frames': [{u'abs_path': u'manage.py',
                                                          u'context_line': u'    execute_from_command_line(sys.argv)',
                                                          u'filename': u'manage.py',
                                                          u'function': u'<module>',
                                                          u'in_app': False,
                                                          u'lineno': 16,
                                                          u'module': u'__main__',
                                                          u'post_context': [],
                                                          u'pre_context': [u'        "DJANGO_SETTINGS_MODULE",',
                                                                           u'        "core.settings.dev")',
                                                                           u'',
                                                                           u'    from django.core.management import execute_from_command_line',
                                                                           u''],
                                                          u'vars': {u'__builtins__': u"<module '__builtin__' (built-in)>",
                                                                    u'__doc__': u"'\ndjango_app.manage\n'",
                                                                    u'__file__': u"'manage.py'",
                                                                    u'__name__': u"'__main__'",
                                                                    u'__package__': None,
                                                                    u'execute_from_command_line': u'<function execute_from_command_line from django.core.management at 0x7f3f9bf6c500>',
                                                                    u'os': u"<module 'os' from '/usr/local/lib/python2.7/os.pyc'>",
                                                                    u'sys': u"<module 'sys' (built-in)>"}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py',
                                                          u'context_line': u'    utility.execute()',
                                                          u'filename': u'django/core/management/__init__.py',
                                                          u'function': u'execute_from_command_line',
                                                          u'in_app': False,
                                                          u'lineno': 354,
                                                          u'module': u'django.core.management',
                                                          u'post_context': [],
                                                          u'pre_context': [u'def execute_from_command_line(argv=None):',
                                                                           u'    """',
                                                                           u'    A simple method that runs a ManagementUtility.',
                                                                           u'    """',
                                                                           u'    utility = ManagementUtility(argv)'],
                                                          u'vars': {u'argv': [u"'manage.py'",
                                                                              u"'collectstatic'",
                                                                              u"'--noinput'"],
                                                                    u'utility': u'<django.core.management.ManagementUtility object at 0x7f3f9bf5cf50>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py',
                                                          u'context_line': u'            self.fetch_command(subcommand).run_from_argv(self.argv)',
                                                          u'filename': u'django/core/management/__init__.py',
                                                          u'function': u'execute',
                                                          u'in_app': False,
                                                          u'lineno': 346,
                                                          u'module': u'django.core.management',
                                                          u'post_context': [u'',
                                                                            u'',
                                                                            u'def execute_from_command_line(argv=None):',
                                                                            u'    """',
                                                                            u'    A simple method that runs a ManagementUtility.'],
                                                          u'pre_context': [u"        elif subcommand == 'version' or self.argv[1:] == ['--version']:",
                                                                           u"            sys.stdout.write(django.get_version() + '\\n')",
                                                                           u"        elif self.argv[1:] in (['--help'], ['-h']):",
                                                                           u"            sys.stdout.write(self.main_help_text() + '\\n')",
                                                                           u'        else:'],
                                                          u'vars': {u'args': [u"'--noinput'"],
                                                                    u'no_settings_commands': [u"u'help'",
                                                                                              u"u'version'",
                                                                                              u"u'--help'",
                                                                                              u"u'--version'",
                                                                                              u"u'-h'",
                                                                                              u"u'compilemessages'",
                                                                                              u"u'makemessages'",
                                                                                              u"u'startapp'",
                                                                                              u"u'startproject'"],
                                                                    u'options': u'Namespace(args=[], pythonpath=None, settings=None)',
                                                                    u'parser': u"CommandParser(prog='manage.py', usage=u'%(prog)s subcommand [options] [args]', description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)",
                                                                    u'self': u'<django.core.management.ManagementUtility object at 0x7f3f9bf5cf50>',
                                                                    u'subcommand': u"'collectstatic'"}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/management/base.py',
                                                          u'context_line': u'            self.execute(*args, **cmd_options)',
                                                          u'filename': u'django/core/management/base.py',
                                                          u'function': u'run_from_argv',
                                                          u'in_app': False,
                                                          u'lineno': 394,
                                                          u'module': u'django.core.management.base',
                                                          u'post_context': [u'        except Exception as e:',
                                                                            u'            if options.traceback or not isinstance(e, CommandError):',
                                                                            u'                raise',
                                                                            u'',
                                                                            u'            # SystemCheckError takes care of its own formatting.'],
                                                          u'pre_context': [u'        else:',
                                                                           u'            options, args = parser.parse_args(argv[2:])',
                                                                           u'            cmd_options = vars(options)',
                                                                           u'        handle_default_options(options)',
                                                                           u'        try:'],
                                                          u'vars': {u'args': [],
                                                                    u'argv': [u"'manage.py'",
                                                                              u"'collectstatic'",
                                                                              u"'--noinput'"],
                                                                    u'cmd_options': {u"'clear'": False,
                                                                                     u"'dry_run'": False,
                                                                                     u"'ignore_patterns'": [u"u'CVS'",
                                                                                                            u"u'.*'",
                                                                                                            u"u'*~'"],
                                                                                     u"'interactive'": False,
                                                                                     u"'link'": False,
                                                                                     u"'no_color'": False,
                                                                                     u"'post_process'": True,
                                                                                     u"'pythonpath'": None,
                                                                                     u"'settings'": None,
                                                                                     u"'traceback'": False,
                                                                                     u"'use_default_ignore_patterns'": True,
                                                                                     u"'verbosity'": 1},
                                                                    u'e': u'ValueError(u"The file \'admin/img/icon-deletelink.svg\' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.",)',
                                                                    u'options': u"Namespace(clear=False, dry_run=False, ignore_patterns=[u'CVS', u'.*', u'*~'], interactive=False, link=False, no_color=False, post_process=True, pythonpath=None, settings=None, traceback=False, use_default_ignore_patterns=True, verbosity=1)",
                                                                    u'parser': u"CommandParser(prog=u'manage.py collectstatic', usage=None, description=u'Collect static files in a single location.', version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)",
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py',
                                                          u'context_line': u'            return original_func(self, *args, **kwargs)',
                                                          u'filename': u'raven/contrib/django/management/__init__.py',
                                                          u'function': u'new_execute',
                                                          u'in_app': False,
                                                          u'lineno': 41,
                                                          u'module': u'raven.contrib.django.management',
                                                          u'post_context': [u'        except Exception:',
                                                                            u'            from raven.contrib.django.models import client',
                                                                            u'',
                                                                            u'            client.captureException(extra={',
                                                                            u"                'argv': sys.argv"],
                                                          u'pre_context': [u'        return False',
                                                                           u'',
                                                                           u'    @wraps(original_func)',
                                                                           u'    def new_execute(self, *args, **kwargs):',
                                                                           u'        try:'],
                                                          u'vars': {u'args': [],
                                                                    u'client': u'<raven.contrib.django.client.DjangoClient object at 0x7f3f896d1e50>',
                                                                    u'kwargs': {u"'clear'": False,
                                                                                u"'dry_run'": False,
                                                                                u"'ignore_patterns'": [u"u'CVS'",
                                                                                                       u"u'.*'",
                                                                                                       u"u'*~'"],
                                                                                u"'interactive'": False,
                                                                                u"'link'": False,
                                                                                u"'no_color'": False,
                                                                                u"'post_process'": True,
                                                                                u"'pythonpath'": None,
                                                                                u"'settings'": None,
                                                                                u"'traceback'": False,
                                                                                u"'use_default_ignore_patterns'": True,
                                                                                u"'verbosity'": 1},
                                                                    u'original_func': u'<unbound method BaseCommand.execute>',
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/management/base.py',
                                                          u'context_line': u'            output = self.handle(*args, **options)',
                                                          u'filename': u'django/core/management/base.py',
                                                          u'function': u'execute',
                                                          u'in_app': False,
                                                          u'lineno': 445,
                                                          u'module': u'django.core.management.base',
                                                          u'post_context': [u'            if output:',
                                                                            u'                if self.output_transaction:',
                                                                            u'                    # This needs to be imported here, because it relies on',
                                                                            u'                    # settings.',
                                                                            u'                    from django.db import connections, DEFAULT_DB_ALIAS'],
                                                          u'pre_context': [u'        try:',
                                                                           u'            if (self.requires_system_checks and',
                                                                           u"                    not options.get('skip_validation') and  # Remove at the end of deprecation for `skip_validation`.",
                                                                           u"                    not options.get('skip_checks')):",
                                                                           u'                self.check()'],
                                                          u'vars': {u'args': [],
                                                                    u'options': {u"'clear'": False,
                                                                                 u"'dry_run'": False,
                                                                                 u"'ignore_patterns'": [u"u'CVS'",
                                                                                                        u"u'.*'",
                                                                                                        u"u'*~'"],
                                                                                 u"'interactive'": False,
                                                                                 u"'link'": False,
                                                                                 u"'no_color'": False,
                                                                                 u"'post_process'": True,
                                                                                 u"'pythonpath'": None,
                                                                                 u"'settings'": None,
                                                                                 u"'traceback'": False,
                                                                                 u"'use_default_ignore_patterns'": True,
                                                                                 u"'verbosity'": 1},
                                                                    u'saved_locale': u"'en-us'",
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>',
                                                                    u'translation': u"<module 'django.utils.translation' from '/usr/local/lib/python2.7/site-packages/django/utils/translation/__init__.pyc'>"}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'context_line': u'        collected = self.collect()',
                                                          u'filename': u'django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'function': u'handle',
                                                          u'in_app': False,
                                                          u'lineno': 168,
                                                          u'module': u'django.contrib.staticfiles.management.commands.collectstatic',
                                                          u'post_context': [u"        modified_count = len(collected['modified'])",
                                                                            u"        unmodified_count = len(collected['unmodified'])",
                                                                            u"        post_processed_count = len(collected['post_processed'])",
                                                                            u'',
                                                                            u'        if self.verbosity >= 1:'],
                                                          u'pre_context': [u'        )',
                                                                           u'',
                                                                           u"        if self.interactive and input(''.join(message)) != 'yes':",
                                                                           u'            raise CommandError("Collecting static files cancelled.")',
                                                                           u''],
                                                          u'vars': {u'destination_path': u"'/home/web/static'",
                                                                    u'message': [u"u'\n'",
                                                                                 u"u'You have requested to collect static files at the destination\nlocation as specified in your settings'",
                                                                                 u"u':\n\n    /home/web/static\n\n'",
                                                                                 u"u'This will overwrite existing files!\n'",
                                                                                 u"u'Are you sure you want to do this?\n\nType 'yes' to continue, or 'no' to cancel: '"],
                                                                    u'options': {u"'clear'": False,
                                                                                 u"'dry_run'": False,
                                                                                 u"'ignore_patterns'": [u"u'CVS'",
                                                                                                        u"u'.*'",
                                                                                                        u"u'*~'"],
                                                                                 u"'interactive'": False,
                                                                                 u"'link'": False,
                                                                                 u"'no_color'": False,
                                                                                 u"'post_process'": True,
                                                                                 u"'pythonpath'": None,
                                                                                 u"'settings'": None,
                                                                                 u"'traceback'": False,
                                                                                 u"'use_default_ignore_patterns'": True,
                                                                                 u"'verbosity'": 1},
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>'}},
                                                         {u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'context_line': u'                    raise processed',
                                                          u'filename': u'django/contrib/staticfiles/management/commands/collectstatic.py',
                                                          u'function': u'collect',
                                                          u'in_app': False,
                                                          u'lineno': 120,
                                                          u'module': u'django.contrib.staticfiles.management.commands.collectstatic',
                                                          u'post_context': [u'                if processed:',
                                                                            u'                    self.log("Post-processed \'%s\' as \'%s\'" %',
                                                                            u'                             (original_path, processed_path), level=1)',
                                                                            u'                    self.post_processed_files.append(original_path)',
                                                                            u'                else:'],
                                                          u'pre_context': [u'                if isinstance(processed, Exception):',
                                                                           u'                    self.stderr.write("Post-processing \'%s\' failed!" % original_path)',
                                                                           u"                    # Add a blank line before the traceback, otherwise it's",
                                                                           u'                    # too easy to miss the relevant part of the error message.',
                                                                           u'                    self.stderr.write("")'],
                                                          u'vars': {u'finder': u'<django.contrib.staticfiles.finders.AppDirectoriesFinder object at 0x7f3f89999d10>',
                                                                    u'handler': u'<bound method Command.copy_file of <django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>>',
                                                                    u'original_path': u"u'grappelli/stylesheets/screen.css'",
                                                                    u'path': u"u'js/github-issue.js'",
                                                                    u'prefixed_path': u"u'js/github-issue.js'",
                                                                    u'processed': u'ValueError(u"The file \'admin/img/icon-deletelink.svg\' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.",)',
                                                                    u'processed_path': None,
                                                                    u'processor': u'<generator object post_process at 0x7f3f8994d780>',
                                                                    u'self': u'<django.contrib.staticfiles.management.commands.collectstatic.Command object at 0x7f3f899f1990>',
                                                                    u'storage': u'<django.core.files.storage.FileSystemStorage object at 0x7f3f89999850>'}}]},
                             u'type': u'ValueError',
                             u'value': u"The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>."}]},
 u'extra': {u'sys.argv': [u"'manage.py'", u"'collectstatic'", u"'--noinput'"]},
 u'level': 40,
 u'message': u"ValueError: The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.",
 u'modules': {u'allauth': u'0.25.2',
              u'crispy_forms': u'1.4.0',
              u'django': u'1.8.12',
              u'django_countries': u'3.4.1',
              u'django_hashedfilenamestorage': u'1.0',
              u'easy_thumbnails': u'2.3',
              u'embed_video': u'1.0.0',
              u'grappelli': u'2.8.1',
              u'python': u'2.7.10',
              u'raven': u'5.8.1',
              u'reversion': u'1.9.3',
              u'rosetta': u'0.7.0'},
 u'platform': u'python',
 u'project': u'8',
 u'server_name': u'uwsgi',
 u'tags': {u'site': u'changelog.kartoza.com'},
 u'time_spent': None,
 u'timestamp': u'2016-04-14T20:17:17Z'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 162, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
ERROR 2016-04-14 22:17:21,981 base 57 139910865270528 [u"ValueError: The file 'admin/img/icon-deletelink.svg' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f3f89a0df50>.", u'  File "manage.py", line 16, in <module>', u'  File "django/core/management/__init__.py", line 354, in execute_from_command_line', u'  File "django/core/management/__init__.py", line 346, in execute', u'  File "django/core/management/base.py", line 394, in run_from_argv', u'  File "raven/contrib/django/management/__init__.py", line 41, in new_execute', u'  File "django/core/management/base.py", line 445, in execute', u'  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle', u'  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect']
make: *** [collectstatic] Error 1

```

# Proposed solution

## Migrations

Can you see how to make a custom migration to add the missing unique constraints. I have actually already run these on the live server too but I am interested to see if there is a better technique for managing this via manually created migrations.

## Collect static

To replicate you should do a ``make collectstatic`` in a production mode setup (on your local machine) and verify that the process runs without any errors. Please chat to me if you need more details to replicate.

**Comment by rischanlab** [comment]
Fixed https://github.com/kartoza/projecta/pull/287
