### ISSUE TITLE
Googlebot 500 when visiting the pending entries list

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#69]
```
Traceback (most recent call last):

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/views/generic/list.py", line 137, in get
    self.object_list = self.get_queryset()

  File "/home/web/projecta/django_project/changes/views/entry.py", line 265, in get_queryset
    return queryset.filter(author=self.request.user)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/query.py", line 590, in filter
    return self._filter_or_exclude(False, *args, **kwargs)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/query.py", line 608, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1198, in add_q
    clause = self._add_q(where_part, used_aliases)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1232, in _add_q
    current_negated=current_negated)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1122, in build_filter
    lookup_type, value)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1105, in get_lookup_constraint
    value[index]), AND)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/utils/tree.py", line 104, in add
    data = self._prepare_data(data)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 79, in _prepare_data
    value = obj.prepare(lookup_type, value)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 352, in prepare
    return self.field.get_prep_lookup(lookup_type, value)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 369, in get_prep_lookup
    return self.get_prep_value(value)

  File "/home/web/projecta/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 613, in get_prep_value
    return int(value)

TypeError: int() argument must be a string or a number, not 'SimpleLazyObject'
```

**Comment by timlinux** [comment]
I think this is fixed now (with hacky try except block).
